export interface RoleType {
    name: string;
    status: boolean;
   }
   
   export const roleItem: RoleType[] = [
    { name: "Destination", status: false },
    { name: "Pop Ups", status: false },
    { name: "SEO", status: false },
    { name: "Crone", status: false },
    { name: "Category Settings", status: false },
    { name: "Gears", status: false },
    { name: "Difficulty", status: false },
    { name: "Season", status: false },
    { name: "Month", status: false },
    { name: "Product Management", status: false },
    { name: "Member Management", status: false },
    { name: "Order Management", status: false },
    { name: "Blog Category", status: false },
    { name: "Blog Comment Setting", status: false },
    { name: "Media", status: false },
    { name: "Company Profile", status: false },
    { name: "Lead Management", status: false },
    { name: "Lead Report", status: false },
    { name: "Tag", status: false },
    { name: "User Management", status: false },
    { name: "Role", status: false },
    { name: "Mailing List", status: false },
    { name: "Page", status: false },
    { name: "Page Sub Category", status: false },
    { name: "Page Category", status: false },
    { name: "Rating", status: false },
    { name: "All Invoice", status: false },
    { name: "Invoice GST", status: false },
    { name: "Career", status: false },
    { name: "Influencer", status: false },
    { name: "Volunteer", status: false },
    { name: "Faq", status: false },
    { name: "Voucher Discount", status: false },
    { name: "Trek For a Cause", status: false },
    { name: "Upcoming Adventure Post", status: false },
    { name: "Adventure Expense Categories", status: false },
    { name: "Advance Amount", status: false },
    { name: "Vendor Summary", status: false },
    { name: "Financial Advance Detail", status: false },
    { name: "Reward Point", status: false },
    { name: "Customization Request", status: false },
    { name: "Push Notification", status: false },
    { name: "Certification Generation", status: false },
    { name: "Whats App Group", status: false },
    { name: "Sticky Note", status: false }
   ];